In [19]:
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [20]:
from scipy.sparse import csr_matrix
train_data = pd.read_csv("/content/drive/My Drive/FTEC_4003_Project/Task_2/preprocessed_train_data.csv")

test_data = pd.read_csv("/content/drive/My Drive/FTEC_4003_Project/Task_2/preprocessed_test_data.csv")

y_train = train_data['Exited']
X_train = train_data.drop(columns=['Exited'])
X_test = test_data.drop(columns=['Exited'])
X_test = X_test.fillna(0)
X_train = csr_matrix(X_train).todense()
X_test = csr_matrix(X_test).todense()

In [21]:
#Use SVM from SVC

from sklearn.svm import SVC
c_list = [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10, 100]

from sklearn.metrics import classification_report, confusion_matrix, roc_curve
from sklearn import metrics
for chosen_c in c_list:
  print('c = ', chosen_c)
  clf = SVC(kernel='rbf', C = chosen_c)
  clf.fit(X_train,y_train)
  y_pred = clf.predict(X_train)
  print(confusion_matrix(y_train,y_pred))
  print(classification_report(y_train,y_pred))
  print(metrics.roc_auc_score(y_train,y_pred))

c =  1e-05
[[5941    0]
 [1559    0]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88      5941
           1       0.00      0.00      0.00      1559

    accuracy                           0.79      7500
   macro avg       0.40      0.50      0.44      7500
weighted avg       0.63      0.79      0.70      7500

0.5
c =  0.0001


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[5941    0]
 [1559    0]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88      5941
           1       0.00      0.00      0.00      1559

    accuracy                           0.79      7500
   macro avg       0.40      0.50      0.44      7500
weighted avg       0.63      0.79      0.70      7500

0.5
c =  0.001


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[5941    0]
 [1559    0]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88      5941
           1       0.00      0.00      0.00      1559

    accuracy                           0.79      7500
   macro avg       0.40      0.50      0.44      7500
weighted avg       0.63      0.79      0.70      7500

0.5
c =  0.01


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[5941    0]
 [1559    0]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88      5941
           1       0.00      0.00      0.00      1559

    accuracy                           0.79      7500
   macro avg       0.40      0.50      0.44      7500
weighted avg       0.63      0.79      0.70      7500

0.5
c =  0.1


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[5941    0]
 [1559    0]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88      5941
           1       0.00      0.00      0.00      1559

    accuracy                           0.79      7500
   macro avg       0.40      0.50      0.44      7500
weighted avg       0.63      0.79      0.70      7500

0.5
c =  1


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[5881   60]
 [1172  387]]
              precision    recall  f1-score   support

           0       0.83      0.99      0.91      5941
           1       0.87      0.25      0.39      1559

    accuracy                           0.84      7500
   macro avg       0.85      0.62      0.65      7500
weighted avg       0.84      0.84      0.80      7500

0.6190683694343534
c =  10
[[5819  122]
 [ 909  650]]
              precision    recall  f1-score   support

           0       0.86      0.98      0.92      5941
           1       0.84      0.42      0.56      1559

    accuracy                           0.86      7500
   macro avg       0.85      0.70      0.74      7500
weighted avg       0.86      0.86      0.84      7500

0.6981993342920156
c =  100
[[5778  163]
 [ 729  830]]
              precision    recall  f1-score   support

           0       0.89      0.97      0.93      5941
           1       0.84      0.53      0.65      1559

    accuracy                           0.88   

In [22]:
clf = SVC(kernel='rbf', C = 100)
clf.fit(X_train,y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [23]:
y_test_pred = clf.predict(X_test)
test_Response = pd.DataFrame(data=y_test_pred, columns=["Response"])
test_Response.index += 342999
test_Response.index.name = 'id'
test_Response.to_csv(r'/content/drive/My Drive/FTEC_4003_Project/Task_2/svc_test_result.csv', index=False)

In [18]:
#Import svm from sgdclassifier
%%time
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import SGDClassifier
from sklearn import metrics

alpha = [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10, 100]

'''
# Use sklearn package
clf = GridSearchCV(SGDClassifier(), tuned_parameters, cv=5, scoring='recall_macro',verbose=1)
clf.fit(X_train, y_train)

print(clf.best_params_)
'''
from sklearn.metrics import classification_report, confusion_matrix, roc_curve
for alph in alpha:
  print('alpha = ', alph)
  clf = SGDClassifier(class_weight='balanced', alpha=alph, penalty='l2', loss='log')
  clf.fit(X_train,y_train)
  y_pred = clf.predict(X_train)
  print(confusion_matrix(y_train,y_pred))
  print(classification_report(y_train,y_pred))
  print(metrics.roc_auc_score(y_train,y_pred))


alpha =  1e-05
[[3388 2553]
 [ 433 1126]]
              precision    recall  f1-score   support

           0       0.89      0.57      0.69      5941
           1       0.31      0.72      0.43      1559

    accuracy                           0.60      7500
   macro avg       0.60      0.65      0.56      7500
weighted avg       0.77      0.60      0.64      7500

0.6462661110930565
alpha =  0.0001
[[4128 1813]
 [ 478 1081]]
              precision    recall  f1-score   support

           0       0.90      0.69      0.78      5941
           1       0.37      0.69      0.49      1559

    accuracy                           0.69      7500
   macro avg       0.63      0.69      0.63      7500
weighted avg       0.79      0.69      0.72      7500

0.6941128602737697
alpha =  0.001
[[4449 1492]
 [ 541 1018]]
              precision    recall  f1-score   support

           0       0.89      0.75      0.81      5941
           1       0.41      0.65      0.50      1559

    accuracy     

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
